ProductsApp/Controllers/SalesOrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Product.DataAccess.Base.Enum;
using Product.DataAccess.Enum;
using Product.DataAccess.Models;
using Product.DataAccess.Repositories;
using Product.DataAccess.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace ProductsApp.Controllers
{
    public class SalesOrdersController : Controller
    {
        private readonly ISalesOrdersRepository _salesOrdersRepository;
        private readonly ISOLinesRepository _soLinesRepository;
        private readonly HttpClient _client;
        private readonly IHttpClientFactory _httpClientFactory;

        public SalesOrdersController(ISalesOrdersRepository salesOrdersRepository, ISOLinesRepository soLinesRepository,IHttpClientFactory httpClientFactory)
        {
            _salesOrdersRepository = salesOrdersRepository;
            _soLinesRepository = soLinesRepository;
            _client = CreateHttpClientWithNTLM();
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> IndexAjax([FromBody] SalesOrdersVM model)
        {
            var resultt = await _client.GetAsync($"{_client.BaseAddress}/SalesOrder?$filter=No eq '{model.SearchNo}'");
            var SalesOrderList = JsonConvert.DeserializeObject<Product.DataAccess.Models.SlaesOrderHeaderAndLines.Rootobject>(await resultt.Content.ReadAsStringAsync());
            if (string.IsNullOrEmpty(model.SearchNo))
            {
                var data = _salesOrdersRepository.GetAllAsyncPage(model.PageNo, model.PageSize,null);
                var SO = data.Item1.Select(v => new SlaesOrderHeaderAndLines.Value()
                {
                    No = v.No,
                    Sell_to_Customer_Name = v.CustomerName,
                    Posting_Description = v.Discription ,
                    SO_Status = v.SOStatus,
                    Order_Date = v.OrderDate.ToString(),
                    Shipment_Date = v.ShipmentDate.ToString(),
                    Phone_No  = v.PhoneNo,
                    CRM_Sales_Amount =Convert.ToInt32(v.Amount)
                }).ToList();
                return Json(new
                {
                    TotalItems = data.Item2,
                    Data = SO
                });
            }
           
            return Json(new
            {
                TotalItems = SalesOrderList.value.Count(),
                Data = SalesOrderList.value
            });
        }
        public IActionResult _Details(string No)
        {
           
         return PartialView(new SalesOrdersVM { No=No });
        }
       
        public async Task<JsonResult> DetailsAjax([FromBody] SalesOrdersVM model)
        {
            var resultt = await _client.GetAsync($"{_client.BaseAddress}/SalesOrder?$filter=No eq '{model.No}'&$expand=SalesOrderSalesLines");
            var SalesOrderList = JsonConvert.DeserializeObject<Product.DataAccess.Models.SlaesOrderHeaderAndLines.Rootobject>(await resultt.Content.ReadAsStringAsync());
            var count = SalesOrderList.value[0].SalesOrderSalesLines.Count();
           
            var isExist = (await _salesOrdersRepository.GetAsync(c => c.No == model.No).ConfigureAwait(false)).Any();
            if (isExist)
            {
                var SO = _salesOrdersRepository.Get(c => c.No == model.No).AsQueryable().FirstOrDefault();//.Include(b=>b.SOLines);
                //var data =  _soLinesRepository.GetAllQuerable();
                var data =  _soLinesRepository.GetAllAsyncPage(model.PageNo, model.PageSize, null);//.Include(c => c.SalesOrders)
                var SOLine = data.Item1.Where(c=>c.SalesOrders.No==model.No).Select(v => new SlaesOrderHeaderAndLines.Salesordersalesline()
                {
                    Line_No =Convert.ToInt32(v.PartNumber),
                    Description = v.Description,
                    Unit_Price =Convert.ToInt32(v.Price),
                    Quantity = Convert.ToInt32(v.Quantity),
                }).ToList();

                return Json(new
                {
                    TotalItems = SOLine.Count(),
                    Data = SOLine
                });
            }
            return Json(new
            {
                TotalItems = count,
                Data = SalesOrderList.value[0].SalesOrderSalesLines
            });
            /* var LineFromDB = _soLinesRepository.GetAllQuerable().Include(c => c.SalesOrderId).Select(v => new {
                 PartNumber = v.PartNumber.ToString(),
                 Description = v.Description,
                 Price = v.Price,
                 Quantity = v.Quantity,
             }).ToList();
             //  var modelVm = _mapper.Map<List<ProductVM>>(data0.Item1);

             return Json(new
             {
                 TotalItems = LineFromDB.Count(),
                 Data = LineFromDB
             });*/
        }
        [HttpPost]
        public async Task<IActionResult> Save(string No)
        {
            var resultt = await _client.GetAsync($"{_client.BaseAddress}/SalesOrder?$filter=No eq '{No}'&$expand=SalesOrderSalesLines");
            var SalesOrderList = JsonConvert.DeserializeObject<SlaesOrderHeaderAndLines.Rootobject>(await resultt.Content.ReadAsStringAsync());
            var data = SalesOrderList.value[0];
            // var SOLine = NotofocationList.value[0].SalesOrderSalesLines;
            var SOLine = SalesOrderList.value[0].SalesOrderSalesLines.ToList();

            var isExist = (await _salesOrdersRepository.GetAsync(c => c.No == data.No ).ConfigureAwait(false)).Any();
            if (isExist)
            {
                // return View(category);
                return Json(new
                {
                    status = JsonStatus.Exist,
                    link = "",
                    color = NotificationColor.Error.ToColorName(),
                    management = "SO Management",
                    msg = "SO is exist."
                });
            }
            else
            {
                var result = await _salesOrdersRepository.AddAsync(new SalesOrders()
                {
                    No = data.No,
                    CustomerName = data.Sell_to_Customer_Name,
                    Discription = data.Posting_Description,
                    SOStatus = data.SO_Status,
                    OrderDate = Convert.ToDateTime(data.Order_Date),
                    ShipmentDate = Convert.ToDateTime(data.Shipment_Date),
                    PhoneNo = data.Phone_No,
                    Amount = data.CRM_Sales_Amount

                });

                if (result > 0)
                {
                    foreach (var line in SOLine)
                    {
                        await _soLinesRepository.AddAsync(new SOLines()
                        {
                            PartNumber = line.Line_No.ToString(),
                            Description = line.Description,
                            Price = line.Unit_Price,
                            Quantity = line.Quantity,
                            SalesOrders = (await _salesOrdersRepository.GetAsync(x => x.No == data.No).ConfigureAwait(false)).FirstOrDefault()
                        });
                    }
                    return Json(new
                    {
                        status = JsonStatus.Success,
                        link = "",
                        color = NotificationColor.Success.ToColorName(),
                        management = "SO Management",
                        msg = "SO was updated successfully into the database.",
                    });
                }
                else
                    return Json(new
                    {
                        status = JsonStatus.Error,
                        link = "",
                        color = NotificationColor.Error.ToColorName(),
                        management = "SO Management",
                        msg = "Error.",
                    });
            }
        }
        public HttpClient CreateHttpClientWithNTLM()
        {
            var url = "http://ns-hou-navdev01.netsync.com:9837/DEVNETSYNC2018/ODataV4/Company(";
         
            var uri = new Uri($"{url}'NetSync%20Network%20-%20Live')");
            var credentialsCache = new CredentialCache { { uri, "NTLM", new NetworkCredential("sales", "Netsync01") } };
            var handler = new HttpClientHandler { Credentials = credentialsCache };
            var httpClient = new HttpClient(handler) { BaseAddress = uri };
            httpClient.DefaultRequestHeaders.ConnectionClose = false;
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            ServicePointManager.FindServicePoint(uri).ConnectionLeaseTimeout = 120 * 1000;  // Close connection after two minutes

            return httpClient;
        }
    }
}

ProductsApp/Views/SalesOrders/Index.cshtml
@model Product.DataAccess.ViewModel.SalesOrdersVM

<div class="row">
    <h4 class="col-sm-10"> All SalesOrders</h4>

    <div class="col-4">
        <div class="kt-input-icon kt-input-icon--left">
            <input type="text" class="form-control  clear-search-input" placeholder="Search..." oninput="refresh();" id="generalSearch">
            <span class="kt-input-icon__icon kt-input-icon__icon--left">
                <span><i class="la la-search"></i></span>
            </span>
        </div>
    </div>
</div>
<br />
<div id="SOGrid" style="width: 100%;height: 100%;" class="ag-theme-balham firefox-scroll-fixed"></div>

<script>

    var columnDefs = [
        {
            headerName: "No", field: "no", editable: false, cellClass: "text-center", headerClass: 'number-header',
            cellRenderer: function (params) {
                if (params.data && params.data != undefined && params.data.no != null && params.data.no != "" && params.data.no != undefined) {
                    return `<a href="SalesOrders/_Details?No=${params.data.no}" ajaxType="GET" class="openModal">${params.data.no}</a>&nbsp;`
                }
                else {
                    return '';
                }
            }
        },
        { headerName: "CustomerName", field: "sell_to_Customer_Name" },
        { headerName: "Description", field: "posting_Description" },
        {
            headerName: "OrderDate", field: "order_Date", cellRenderer: (data) => {
                return data.value ? (new Date(data.value)).toLocaleDateString() : '';
            }
        },
        {
            headerName: "ShipmentDate", field: "shipment_Date", cellRenderer: (data) => {
                return data.value ? (new Date(data.value)).toLocaleDateString() : '';
            }
        },
        { headerName: "PhoneNo", field: "phone_No" },
        { headerName: "Amount", field: "crM_Sales_Amount" },

    ];

    var gridOptions = {
        columnDefs: columnDefs,
        rowSelection: 'multiple',
        domLayout: 'autoHeight',

        defaultColDef: {
            editable: false,
            enableRowGroup: true,
            enablePivot: true,
            enableValue: true,
            sortable: true,
            resizable: true,
            filter: true,
            flex: 1
        },
        suppressRowClickSelection: true,
        pagination: true,
        getRowHeight: function (params) {
            return 35;
        },
        rowModelType: 'infinite',
        animateRows: true,
        paginationPageSize: 3,
        cacheOverflowSize: 2,
        maxConcurrentDatasourceRequests: 2,
        infiniteInitialRowCount: 1,
        maxBlocksInCache: 2,
        cacheBlockSize: 3,
        enableColResize: true,
        suppressMenuHide: true,
        onGridReady: function () {
            gridOptions.api.sizeColumnsToFit();
        }, 
    };
    var dataSourceTest = '';
    document.addEventListener('DOMContentLoaded', function () {
        var gridDiv = document.querySelector('#SOGrid');
        new agGrid.Grid(gridDiv, gridOptions);

        dataSourceTest = {
            //  rowCount: null, // behave as infinite scroll
            getRows: function (params) {
                var model = {
                    PageNo: gridOptions.api.paginationGetCurrentPage(),
                    PageSize: gridOptions.paginationPageSize,
                    SearchNo: document.getElementById('generalSearch').value,
                };
                loadPaginatedGridWithDelay('/SalesOrders/IndexAjax', 'POST', model, gridOptions, params);
            },
            getRowHeight: function (params) {
                return 35;
            },
        };
        gridOptions.api.showNoRowsOverlay();
        gridOptions.api.setDatasource(dataSourceTest);
    });


    function refresh(e) {
        gridOptions.api.setDatasource(dataSourceTest);
    }
</script>

ProductsApp/Views/SalesOrders/_Details.cshtml
@model Product.DataAccess.ViewModel.SalesOrdersVM


<div class="modal-header">

    <h5 class="modal-title" id="exampleModalLabel">SO Lines for  @Model.No</h5>
    
    <form asp-action="Save" method="post" asp-controller="SalesOrders" class="ajaxForm">
        <input type="hidden" asp-for="No" />
        <button type="submit" asp-action="Save" asp-route-No="@Model.No" class="btn btn-sm btn-outline-success"> Save to database</button>
    </form>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

</div>
<div class="modal-body">
    <input type="hidden" asp-for="No" id="No" />
    <div class="container">
        <br />
        <div class="row">
            <div id="SOLineGrid" style="height:55vh;width:100%" class="ag-theme-balham firefox-scroll-fixed"></div>

        </div>

        <br />

    </div>
</div>

<div class="modal-footer">
    <div class="row">
        <div class="col-md-12">
            <div class="float-right">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>&nbsp;
            </div>
        </div>
    </div>
</div>

<script>
    var columnDefs = [
        { headerName: "Part", field: "line_No" },
        { headerName: "Description", field: "description" },
        { headerName: "Quantity", field: "quantity" },
        { headerName: "Price", field: "unit_Price" },
    ];

    var gridOptions = {
        columnDefs: columnDefs,
        rowSelection: 'multiple',
        domLayout: 'autoHeight',

        defaultColDef: {
            editable: false,
            enableRowGroup: true,
            enablePivot: true,
            enableValue: true,
            sortable: true,
            resizable: true,
            filter: true,
            flex: 1
        },
        suppressRowClickSelection: true,
        pagination: true,
        getRowHeight: function (params) {
            return 35;
        },
        rowModelType: 'infinite',
        animateRows: true,
        paginationPageSize: 3,
        cacheOverflowSize: 2,
        maxConcurrentDatasourceRequests: 2,
        infiniteInitialRowCount: 1,
        maxBlocksInCache: 2,
        cacheBlockSize: 3,
        enableColResize: true,
        suppressMenuHide: true,
        onGridReady: function () {
            gridOptions.api.sizeColumnsToFit();
        }, 

    };
    var dataSourceTest = '';
    $(document).ready(function () {
        var gridDiv = document.querySelector('#SOLineGrid');
        new agGrid.Grid(gridDiv, gridOptions);
        dataSourceTest = {
            //  rowCount: null, // behave as infinite scroll
            getRows: function (params) {
                var model = {
                    PageNo: gridOptions.api.paginationGetCurrentPage(),
                    PageSize: gridOptions.paginationPageSize,
                    No: document.getElementById('No').value,
                };
                loadPaginatedGridWithDelay('/SalesOrders/DetailsAjax', 'POST', model, gridOptions, params);

            },
            getRowHeight: function (params) {
                return 35;
            },
        };
        gridOptions.api.showNoRowsOverlay();
        gridOptions.api.setDatasource(dataSourceTest);
    });


    function refresh(e) {
        gridOptions.api.setDatasource(dataSourceTest);
    }

</script>