ProductsApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Product.DataAccess.Data;
using Product.DataAccess.Models;
using Product.DataAccess.Repositories;
using Product.DataAccess.ViewModel;
using AutoMapper;
using Product.DataAccess.Enum;
using Product.DataAccess.Base.Enum;

namespace ProductsApp.Controllers
{
   
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IMapper _mapper;

        public CategoriesController(ICategoryRepository categoryRepository, IMapper mapper)
        {
            _categoryRepository = categoryRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IndexAjax([FromBody] CategoryVM model)
        {
            var data = _categoryRepository.GetAllAsyncPage(model.PageNo, model.PageSize, c => c.Name.ToLower().Contains(model.SearchText));
            // return Json(data.Item1);
            var modelVm = _mapper.Map<List<CategoryVM>>(data.Item1);
           
            return Json(new
            {
                TotalItems = data.Item2,
                Data = modelVm
            });
        }
        public async Task<IActionResult> _Details(int id)
        {
            var category = await _categoryRepository.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return PartialView(_mapper.Map<CategoryVM>(category));
        }

        public IActionResult _Create()
        {
            var model = new CategoryVM{};
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryVM category)
        {
            
            if (ModelState.IsValid)
            {
            var isExist = _categoryRepository.Get(c => c.Name == category.Name).Count() > 0;
            if (isExist)
                return Json(new
                {
                    status = JsonStatus.Exist,
                    link = "",
                    color = NotificationColor.Error.ToColorName(),
                    management = "Category Management",
                    msg = "Category is exist.",
                    editResult = category
                });                
                await _categoryRepository.AddAsync(_mapper.Map<Category>(category));
              
                return Json(new
                {
                    status = JsonStatus.Success,
                    link = "",
                    color = NotificationColor.Success.ToColorName(),
                    management = "Category Management",
                    msg = "Category was updated successfully into the database.",
                    editResult = category
                });
            }
            return Json(new
            {
                status = JsonStatus.Exist,
                link = "",
                color = NotificationColor.Error.ToColorName(),
                management = "Category Management",
                msg = ModelState.Keys.SelectMany(k => ModelState[k].Errors)
                                                    .Select(m => m.ErrorMessage).ToArray()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryVM category)
        {
            if (ModelState.IsValid)
            {
                var isExist = (await _categoryRepository.GetAsync(c => c.Name.ToLower() == category.Name.ToLower() && c.Id != category.Id).ConfigureAwait(false)).Any();
                if (isExist)
                    // return View(category);
                    return Json(new
                    {
                        status = JsonStatus.Exist,
                        link = "",
                        color = NotificationColor.Error.ToColorName(),
                        management = "Category Management",
                        msg = "Category is exist."
                    });
             
                await _categoryRepository.UpdateAsync(_mapper.Map<Category>(category));
                // return RedirectToAction(nameof(Index));
                return Json(new
                {
                    status = JsonStatus.Success,
                    link = "",
                    color = NotificationColor.Success.ToColorName(),
                    management = "Category Management",
                    msg = "Category was updated successfully into the database."
                });
            }

            return Json(new
            {
                status = JsonStatus.Exist,
                link = "",
                color = NotificationColor.Error.ToColorName(),
                management = "Category Management",
                msg = ModelState.Keys.SelectMany(k => ModelState[k].Errors)
                                         .Select(m => m.ErrorMessage).ToArray()
            });
        }
        public async Task<IActionResult> _Edit(int id)
        {
            var model = await _categoryRepository.FindAsync(id).ConfigureAwait(false);
            var modelVm = _mapper.Map<CategoryVM>(model);
            
            return PartialView(modelVm);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _categoryRepository.FindAsync(id).ConfigureAwait(false);
            await _categoryRepository.RemoveAsync(model).ConfigureAwait(false);

            return Json(new
            {
                status = JsonStatus.Success,
                link = "",
                color = NotificationColor.Success.ToColorName(),
                management = "category",
                msg = "category was deleted successfully form the database."
            });
        }
     
    }
}

ProductsApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Product.DataAccess.Repositories;
using Product.DataAccess.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Product.DataAccess.ViewModel;
using AutoMapper;
using System.Globalization;
using Product.DataAccess.Enum;
using Product.DataAccess.Base.Enum;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace ProductsApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _env;
        private readonly IMapper _mapper;

        public ProductController(IWebHostEnvironment env,IProductRepository productRepository, ICategoryRepository categoryRepository, IMapper mapper)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _mapper = mapper;
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult IndexAjax([FromBody] ProductVM model)
        {
            var data0 = _productRepository.GetAllAsyncPage(model.PageNo, model.PageSize
                , c => c.Name.ToLower().Contains(model.SearchText));
            var data = data0.Item1.Include(c => c.Category).Select(v => new {
                    Id=v.Id,
                    Name = v.Name,
                    InsertedDate = v.InsertedDate,
                    Price = v.Price,
                    Code = v.Code,
                    ProdCat = v.Category.Name
                }).ToList();
          //  var modelVm = _mapper.Map<List<ProductVM>>(data0.Item1);

            return Json(new
            {
                TotalItems = data0.Item2,
                Data = data
            });
        }
      
        public async Task<IActionResult> _Details(int? id)
        {
            var product = await _productRepository.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return PartialView(_mapper.Map<ProductVM>(product));
        }

        public IActionResult _Create()
        {
            
          
            var model = new ProductVM
            {
                CategoryList = _categoryRepository.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }).ToList()
            };
            return PartialView(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductVM product)
        {
            product.InsertedDate = DateTime.Now.Date;
            // product.StartDateFormatted = DateTime.ParseExact(product.StartDateFormatted, "MM/dd/yyyy", CultureInfo.InvariantCulture); 

            if (ModelState.IsValid)
            {
                if (product.files != null)
                {
                    product.Image = UploadFile(product.files, null, null);
                }
                var isExist = (await _productRepository.GetAsync(c => c.Name.ToLower() == product.Name.ToLower()).ConfigureAwait(false)).Any();
                if (isExist)
                    return Json(new
                    {
                        status = JsonStatus.Exist,
                        link = "",
                        color = NotificationColor.Error.ToColorName(),
                        management = "product Management",
                        msg = "product is exist.",
                    });
                var test = _mapper.Map<Products>(product);
                test.Category = (await _categoryRepository.GetAsync(x => x.Id == product.CategoryId)).FirstOrDefault();

                await _productRepository.AddAsync(test);

                return Json(new
                {
                    status = JsonStatus.Success,
                    link = "",
                    color = NotificationColor.Success.ToColorName(),
                    management = "product Management",
                    msg = "product was created successfully into the database.",
                });
            }
            return Json(new
            {
                status = JsonStatus.Exist,
                link = "",
                color = NotificationColor.Error.ToColorName(),
                management = "product Management",
                msg = ModelState.Keys.SelectMany(k => ModelState[k].Errors)
                                                    .Select(m => m.ErrorMessage).ToArray()
            });
        }

        public async Task<IActionResult> _Edit(int id)
        {

            var product = await _productRepository.FindAsync(id);
            if (product == null)
            {
                return Json(new
                {
                    status = JsonStatus.Exist,
                    link = "",
                    color = NotificationColor.Error.ToColorName(),
                    management = "product Management",
                    msg = "product Not found."
                });
            }
            var modelVm = _mapper.Map<ProductVM>(product);

            modelVm.CategoryList= 
                 _categoryRepository.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }).ToList();
            return PartialView(modelVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductVM product)
        {
           
            if (ModelState.IsValid)
            {
                // string oldfilePath = product.files.FileName;
                if (product.files != null)
                {
                    product.Image = UploadFile(product.files, product.Image,product.Id.ToString());
                }
                var isExist = (await _productRepository.GetAsync(c => c.Name.ToLower() == product.Name.ToLower() && c.Id != product.Id).ConfigureAwait(false)).Any();
                if (isExist)
                    // return View(category);
                    return Json(new
                    {
                        status = JsonStatus.Exist,
                        link = "",
                        color = NotificationColor.Error.ToColorName(),
                        management = "product Management",
                        msg = "product is exist."
                    });
                //  Products model = await _productRepository.FindAsync(product.Id).ConfigureAwait(false);
              var test = _mapper.Map<Products>(product);
              test.Category = (await _categoryRepository.GetAsync(x => x.Id == product.CategoryId)).FirstOrDefault();

                await _productRepository.UpdateAsync(test);
                return Json(new
                {
                    status = JsonStatus.Success,
                    link = "",
                    color = NotificationColor.Success.ToColorName(),
                    management = "product Management",
                    msg = "product was updated successfully into the database."
                });
            }

            return Json(new
            {
                status = JsonStatus.Exist,
                link = "",
                color = NotificationColor.Error.ToColorName(),
                management = "product Management",
                msg = ModelState.Keys.SelectMany(k => ModelState[k].Errors)
                                         .Select(m => m.ErrorMessage).ToArray()
            });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _productRepository.FindAsync(id).ConfigureAwait(false);
            await _productRepository.RemoveAsync(model).ConfigureAwait(false);

            return Json(new
            {
                status = JsonStatus.Success,
                link = "",
                color = NotificationColor.Success.ToColorName(),
                management = "category",
                msg = "category was deleted successfully form the database."
            });
        }

        public string  UploadFile(IFormFile file,string img,string id)
        {

            if (img != null)
            {
                //string fileName = _productRepository.Find(id).Image;
                string FilePathOld = Path.Combine(_env.WebRootPath, "ProductImages", img);
                if (System.IO.File.Exists(FilePathOld))
                {
                    System.IO.File.Delete(FilePathOld);
                }
            }
            string FileNameUploader = Path.Combine(_env.WebRootPath, "ProductImages");
            if (!Directory.Exists(FileNameUploader))
            {
                Directory.CreateDirectory(FileNameUploader);
            }
            string UniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
           // string UniqueFileName = id + "_" + file.FileName;
            string FilePath = Path.Combine(FileNameUploader, UniqueFileName);

            file.CopyTo(new FileStream(FilePath, FileMode.Create));
            return UniqueFileName;
        }
    }
}

ProductsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalesOrders</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap4-toggle.min.css" rel="stylesheet" />
    @* <link href="~/content/toastr.css" rel="stylesheet" />
    *@
    <link href="~/img/plugins.bundle.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha256-R91pD48xW+oHbpJYGn5xR0Q7tMhH4xOrWn1QqMRINtA=" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SalesOrders</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <div class="main-menu f-left">
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
            <a class="nav-link" asp-controller="Product" asp-action="Index">All Products</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Categories" asp-action="Index">All Categories</a>
        </li>
                                    <partial name="_ProductMenu" />
                            *@
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="SalesOrders" asp-action="Index">All SalesOrders</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer pl-3 text-white-50" style="background-color:#343a40;">
        <div class="container">
            &copy; 2020 - SalesOrders
        </div>
    </footer>

    <div class="modal fade" id="OpenModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content modal-scroll-content">

            </div>
        </div>
    </div>

    <script>
        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#22b9ff",
                    "light": "#ffffff",
                    "dark": "#282a3c",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995"
                },
                "base": {
                    "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
                    "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
                }
            }
        };
    </script>
    @*<script src="~/scripts/toastr.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <script src="https://cdn.tiny.cloud/1/mfo7rbk1ak4f0whljnl87rt4wtrcn23vtmqeqiv8fmy6mop5/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap4-toggle.min.js"></script>
    <script src="~/img/plugins.bundle.js"></script>
    <script src="~/lib/Jquery-overlaysScrollbars/jquery.overlayScrollbars.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha256-yNbKY1y6h2rbVcQtf0b8lq4a+xpktyFc3pSYoGAY1qQ=" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ProductsApp/Views/Shared/_ProductMenu.cshtml
@inject Product.DataAccess.Repositories.ICategoryRepository _category;
@inject Product.DataAccess.Repositories.IProductRepository _product;
@{
    var products =await _product.GetAllAsync();
    var categories =await _category.GetAllAsync();

}
<li class="mega-position nav-item dropdown text-white-50">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropDowmMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Product Managment
    </a>
    <div class="dropdown-menu col-lg-8 sub-menu-segment-border">
        @foreach (var category in categories)
        {
            <div class="col-lg-3">
                <ul class="multi-column-dropdown">
                    <li class="active has-sub menu-title uppercase">
                        <a href="#"><span>@category.Name</span></a>
                        <ul>
                            @foreach (var product in products.Where(x => category.Id == x.CategoryId))
                            {
                                <li class="has-sub"><a href="/Product/_Details/@product.Id"><span>@product.Name</span></a></li>

                            }
                        </ul>

                    </li>
                </ul>
            </div>
        }
    </div>
</li>